import { NotebookPen } from 'lucide-react';
import type { Metadata } from 'next';
import { Geist, Geist_Mono, Inter } from 'next/font/google';
import { cn } from '@/lib/utils';
import './globals.css';

const inter = Inter({ subsets: ['latin'], variable: '--font-sans' });

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export function AppHeader() {
  return (
    <header className="w-full bg-white/50 backdrop-blur-md dark:bg-black/50 border-b border-zinc-200 dark:border-zinc-800">
      <div className="container mx-auto flex gap-2 h-16 items-center px-4 sm:px-6 lg:px-8">
        <NotebookPen className="text-zinc-900 dark:text-zinc-100" />
        <h1 className="text-lg font-bold text-zinc-900 dark:text-zinc-100">ECC Chamada</h1>
      </div>
    </header>
  );
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={cn('h-full', 'antialiased', geistSans.variable, geistMono.variable, 'font-sans', inter.variable)}
    >
      <body className="min-h-full flex flex-col">
        <AppHeader />
        <main className="container mx-auto py-4 sm:px-6 lg:px-8">{children}</main>
      </body>
    </html>
  );
}
